
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-upload-process-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-upload-process-deployment
  template:
    metadata:
      labels:
        app: ms-upload-process-deployment
    spec:
      containers:
      - name: ms-upload-process
        image: rmontoza/msuploadprocess:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: ms-upload-process-config
              key: MONGODB_URI
        volumeMounts:
        - name: ms-upload-process-volume
          mountPath: /app
        ##command: ["/start-web.sh"]  # Substitua isso pelo comando de início apropriado, se necessário
      volumes:
      - name: ms-upload-process-volume
        emptyDir: {}
